function onLoading(){function p(a,b){var c=[];c.push(a.dim.y+b.dim.y-(Math.max(a.points[0].y,a.points[2].y,b.points[2].y,b.points[0].y)-Math.min(a.points[0].y,a.points[2].y,b.points[2].y,b.points[0].y)));c.push(a.dim.x+b.dim.x-(Math.max(a.points[0].x,a.points[1].x,b.points[1].x,b.points[0].x)-Math.min(a.points[0].x,a.points[1].x,b.points[1].x,b.points[0].x)));return 0<c[0]&&0<c[1]?c[0]<c[1]?a.points[2].y==Math.max(a.points[0].y,a.points[2].y,b.points[2].y,b.points[0].y)?new d(0,c[0]+0.01):new d(0,
-(c[0]+0.01)):a.points[1].x==Math.max(a.points[0].x,a.points[1].x,b.points[1].x,b.points[0].x)?new d(c[1]+0.01,0):new d(-(c[1]+0.01),0):new d(0,0)}function j(a){if("mouseup"==a.type){var b=q(new d(j.startPos.x,j.startPos.y)),c=q(new d(a.offsetX-j.startPos.x,a.offsetY-j.startPos.y));0>c.x&&(b.x+=c.x,c.x*=-1);0>c.y&&(b.y+=c.y,c.y*=-1);new h(b,c,"#514949")}else"mousedown"==a.type&&(j.startPos.x=a.offsetX,j.startPos.y=a.offsetY);console.log(a.offsetX+" "+a.offsetY)}function k(){for(var a=0;a<f.width;a+=
k.space)g.moveTo(a,0),g.lineTo(a,f.height);for(a=0;a<f.height;a+=k.space)g.moveTo(0,a),g.lineTo(f.width,a)}function q(a){a.x=Math.round(a.x/k.space)*k.space;a.y=Math.round(a.y/k.space)*k.space;return a}function d(a,b){this.x=a;this.y=b;this.scaleMult=function(a){return new d(this.x*a,this.y*a)};this.copy=function(){return new d(this.x,this.y)};this.add=function(a){return new d(this.x+a.x,this.y+a.y)}}function h(a,b,c){this.pos=a;this.dim=b;h.ar.push(this);this.draw=function(){g.fillStyle=this.color;
g.fillRect(this.pos.x,this.pos.y,this.dim.x,this.dim.y)};this.calcPoints=function(){for(var a=0;2>a;a++)for(var b=0;2>b;b++)this.points[2*a+b]=new d(this.pos.x+b*this.dim.x,this.pos.y+a*this.dim.y)};this.points=[];this.calcPoints();this.color=c}var g,f,l,e=Array(4);j.startPos=new d(0,0);k.space=30;var r=0;h.ar=[];f=document.getElementById("myCanvas");g=f.getContext("2d");l=new function(){this.dt=this.time=0;this.getTimePassed=function(){var a=(new Date).getTime();this.dt=a-(this.time||a);this.time=
a;this.dt/=15;r<this.dt&&(r=this.dt);1.6<this.dt&&(this.dt=0)}};f.focus();f.addEventListener("keydown",function(a){a="which"in a?a.which:a.keyCode;87==a&&(e[0]=!0);65==a&&(e[1]=!0);83==a&&(e[2]=!0);68==a&&(e[3]=!0)},!0);f.addEventListener("keyup",function(a){a="which"in a?a.which:a.keyCode;87==a&&(e[0]=!1);65==a&&(e[1]=!1);83==a&&(e[2]=!1);68==a&&(e[3]=!1)},!0);f.addEventListener("mousedown",j,!0);f.addEventListener("mouseup",j,!0);var m=new function(a,b,c){this.pos=a;this.dim=b;this.calcPoints=function(){for(var a=
0;2>a;a++)for(var b=0;2>b;b++)this.points[2*a+b]=new d(this.pos.x+b*this.dim.x,this.pos.y+a*this.dim.y)};this.move=function(){this.spd.y+=0.3*l.dt;this.pos=this.pos.add(this.spd.scaleMult(l.dt));this.calcPoints();this.grounded=!1;for(var a=[],b=[],c=0;c<h.ar.length;c++){var d=p(this,h.ar[c]);this.pos=this.pos.add(d);this.calcPoints();for(var g=!0,f=0;f<h.ar.length;f++)if(h.ar[f]!=h.ar[c]){var e=p(this,h.ar[f]);if(0!=e.x||0!=e.y)if(-1!=a.indexOf(h.ar[f]))this.pos=this.pos.add(e),0!=e.y?0>e.y!=0>this.spd.y&&
(this.spd.y=0,0>e.y&&(this.grounded=!0,this.jumpsDone=0)):0!=e.x&&0>e.x!=0>this.spd.x&&(this.spd.x=0);else{a.push(h.ar[c]);b.push(e);this.pos=this.pos.add(d.scaleMult(-1));this.calcPoints();g=!1;break}}g&&(0!=d.y?0>d.y!=0>this.spd.y&&(this.spd.y=0,0>d.y&&(this.grounded=!0,this.jumpsDone=0)):0!=d.x&&0>d.x!=0>this.spd.x&&(this.spd.x=0))}this.calcPoints()};this.checkInput=function(){console.log(this.grounded);e[0]?this.jumpsDone<this.maxJumps&&!this.jumpKeyDown&&(this.spd.y=-7,this.jumpsDone++,this.jumpKeyDown=
!0):this.jumpKeyDown=!1;e[2]&&(this.spd.y=5);e[1]&&this.spd.x>-this.maxSpd&&(this.spd.x-=0.7*l.dt);e[3]&&this.spd.x<this.maxSpd&&(this.spd.x+=0.7*l.dt)};this.draw=function(){g.fillStyle=this.color;g.fillRect(this.pos.x,this.pos.y,this.dim.x,this.dim.y)};this.grounded=!1;this.maxJumps=2;this.jumpsDone=0;this.jumpKeyDown=!1;this.points=[];this.calcPoints();this.maxSpd=3;this.spd=new d(0,0);this.color=c}(new d(200,200),new d(30,30),"#FF0000");new h(new d(300,300),new d(30,90),"#514949");new h(new d(0,
450),new d(600,30),"#514949");var s=function(){g.clearRect(0,0,f.width,f.height);l.getTimePassed();m.checkInput();m.move();m.draw();g.save();g.translate(1,0);g.save();g.restore();for(var a=0;a<h.ar.length;a++)h.ar[a].draw();g.beginPath();k();g.stroke()},n=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||null;if(null!==n){var t=function(){s();n(t,f)};n(t,f)}else setInterval(s,1E3/60)};
